// <auto-generated />
using System;
using DataRange.DAL.DbContex;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DataRange.DAL.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20200315155243_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DataRange.DAL.Entities.NoteDates", b =>
                {
                    b.Property<int>("DataId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("FirstData");

                    b.Property<DateTime>("LastData");

                    b.Property<int>("UserId");

                    b.HasKey("DataId");

                    b.HasIndex("UserId");

                    b.ToTable("NoteDates");
                });

            modelBuilder.Entity("DataRange.DAL.Entities.Users", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Password");

                    b.Property<string>("UserName");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasData(
                        new { UserId = 1, Password = "fEqNCco3Yq9h5ZUglD3CZJT4lBs=", UserName = "StarBax" }
                    );
                });

            modelBuilder.Entity("DataRange.DAL.Entities.NoteDates", b =>
                {
                    b.HasOne("DataRange.DAL.Entities.Users", "Users")
                        .WithMany("NoteDates")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
